language: node_js

node_js:
  - "8"

# 缓存依赖
cache:
  directories:
    - $HOME/.npm

install:
  - npm install

script:
  - npm run doc

branches:
  only:
    - master

# GitHub Pages 部署
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  name: $GIT_NAME
  email: $GIT_EMAIL
  on:
    branch: master
